"""Agent Plugins 1.0.0 loader and the tiny-harness namespace directory (R3)."""

from tiny_harness.harness.plugins.loader import (
    PluginLoader,
    Registrar,
    contained,
    discover,
    expand,
    parse_manifest,
    parse_mcp,
    prepare_stdio,
    resolve_cwd,
)
from tiny_harness.harness.plugins.models import (
    MCP_SCHEMA_ID,
    NAMESPACE,
    PLUGIN_DATA_VAR,
    PLUGIN_ROOT_VAR,
    PLUGIN_SCHEMA_ID,
    Author,
    ComponentKind,
    HookDef,
    HooksFile,
    LoadedComponent,
    LoadReport,
    McpConfig,
    McpHttpServer,
    McpServer,
    McpSseServer,
    McpStdioServer,
    Plugin,
    PluginManifest,
    PluginName,
    SkippedComponent,
)

__all__ = [
    "MCP_SCHEMA_ID",
    "NAMESPACE",
    "PLUGIN_DATA_VAR",
    "PLUGIN_ROOT_VAR",
    "PLUGIN_SCHEMA_ID",
    "Author",
    "ComponentKind",
    "HookDef",
    "HooksFile",
    "LoadReport",
    "LoadedComponent",
    "McpConfig",
    "McpHttpServer",
    "McpServer",
    "McpSseServer",
    "McpStdioServer",
    "Plugin",
    "PluginLoader",
    "PluginManifest",
    "PluginName",
    "Registrar",
    "SkippedComponent",
    "contained",
    "discover",
    "expand",
    "parse_manifest",
    "parse_mcp",
    "prepare_stdio",
    "resolve_cwd",
]
